
//const ISLOCAL = true;
//const SERVER_PORT = 5001;
// const serverURL = ISLOCAL ? `http://localhost:${SERVER_PORT}` : "https://3a51-156-146-107-197.ngrok-free.app";

let settings = [
  { key: "darkMode", value: true },
  { key: "cloudMode", value: false },
  { key: "AHKPath", value: 'C:\\Program Files\\AutoHotkey\\v2\\AutoHotkey.exe' },
  { key: "focusExplorerPath", value: 'C:\\Users\\andre\\focusExplorer.ahk' },


  { key: "m3u8Notifs", value: true },
  { key: "mp4Notifs", value: false },
  { key: "m4aNotifs", value: false },
  { key: "failureNotifs", value: false },
  { key: "playlistNotifs", value: true },

  { key: "outputPath", value: 'C:\\Users\\andre\\Downloads\\Descargo' },
  { key: "removeSubtext", value: true },
  { key: "normalizeAudio", value: false },
  { key: "useShazam", value: false },
  { key: "generateSubs", value: false },
  { key: "useAria2c", value: false },
  { key: "maxDownloads", value: '10' },

  { key: "gdriveJSONKey", value: 'C:\\Users\\andre\\OneDrive\\Documents\\Webdev\\descargo\\server\\keys\\yt-dl-443015-d39da117fe4a.json' },
  { key: "gdriveFolderID", value: '17pMCBUQxJfEYgVvNwKQUcS8n4oRGIE9q' },
  { key: "cookiePath", value: "C:\\Users\\andre\\OneDrive\\Documents\\cookies.firefox-private.txt" },
  { key: "gdriveKeyText", value: "" },
  {
    key: "cookieText", value: `
    # Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.google.com	TRUE	/	FALSE	1769403021	APISID	RFPxGDJb7Teqksih/A_bpnGpnkJcdURjra
.google.com	TRUE	/	FALSE	1769403021	HSID	AQryqU-QBv0P8zvWg
.google.com	TRUE	/	TRUE	1769403021	SAPISID	4LXuTHdZJYTeV6z0/AF3tq8myo2ooe1R7X
.google.com	TRUE	/	FALSE	1769403021	SID	g.a000rgj0wk5KVoDjTbPmoqJ2hX9wqIKxO8luiwJHbkZD6vhAHQv26HMnVWMXc40V5IP3sTr48wACgYKAUASARISFQHGX2MiIsI54i4iZ-OJo8tnX-Jp-xoVAUF8yKrIogqu9CxqEJ6w90mlD0rq0076
.google.com	TRUE	/	FALSE	1766379021	SIDCC	AKEyXzVt6sZdKbS291LUiDlzLvPw8mvzSQBPF8a8VDMmZ1fTgV_FWYtvbDbZ52SJAbAIN68f4w
.google.com	TRUE	/	TRUE	1769403021	SSID	AH8An8-SHoVJFeYJl
.google.com	TRUE	/	TRUE	1769403021	__Secure-1PAPISID	4LXuTHdZJYTeV6z0/AF3tq8myo2ooe1R7X
.google.com	TRUE	/	TRUE	1769403021	__Secure-1PSID	g.a000rgj0wk5KVoDjTbPmoqJ2hX9wqIKxO8luiwJHbkZD6vhAHQv2d517IL2x9ynMRnxyQA8z4gACgYKAdESARISFQHGX2MiAfIBepA5za1RQYbyS_qJMxoVAUF8yKpFivBSlL80eCEL6z5lrOqv0076
.google.com	TRUE	/	TRUE	1766379021	__Secure-1PSIDCC	AKEyXzU3gMTN9h98e0snwhHfbK-PeNdQb1_v_0POgVQNj4MgTwNkhGuZhf0KXv8bSxFgqzaT
.google.com	TRUE	/	TRUE	1769403021	__Secure-3PAPISID	4LXuTHdZJYTeV6z0/AF3tq8myo2ooe1R7X
.google.com	TRUE	/	TRUE	1769403021	__Secure-3PSID	g.a000rgj0wk5KVoDjTbPmoqJ2hX9wqIKxO8luiwJHbkZD6vhAHQv2fSnSI0BLGvNdAl4jTiE65gACgYKAdQSARISFQHGX2MiPTIzzDuhQPDm3u8NruLX4RoVAUF8yKqN48TY0NzrWX1CMDQdGXCq0076
.google.com	TRUE	/	TRUE	1766379021	__Secure-3PSIDCC	AKEyXzWSJbpbwHWDjGWqSTKDNF-gvtu8xQ_Zhn4DG5zXjJSqkIEJEdUSPq72yWDa1XG0ireOeQ
.youtube.com	TRUE	/	FALSE	1769403022	APISID	RFPxGDJb7Teqksih/A_bpnGpnkJcdURjra
.youtube.com	TRUE	/	FALSE	1769403022	HSID	AJmRz3zOEvGx_AAIQ
.youtube.com	TRUE	/	TRUE	1769403022	LOGIN_INFO	AFmmF2swRAIgQbexx_xf623U3yVHXk5MWi-tJXqs7C424wEV-i9MaKUCIFw81qAtm0Uh8bZ9yGyqfoR6GZ0NHs9YQwXxcGhxkPCW:QUQ3MjNmeUxCZ0hPQVJRZXo2OEhNTk05Q29CSXN2WlNBYTRzaHBIRzMzSm42ZDlINVlPVlZnQWdjLV9vZE0xOC1QUUZTcmoyVVROZ0UxSEk2RHdZTHlFYTdMWTQ1UzJWZEU2MHJhVkhoSGk1dUxjYUhZMXJUblgyaVp6QWU3NHdjak40NS1vbE8wSjN0X2NMSmlpak90NGdkVDFRQ0V6ZE83Rl9YVFlvVzctRExwLWYtVTJ5U2dwSlJWelJJME14XzktUFBPVnh4a2JfdjU2MjQ3NlpXYlc2Nk03Zmc4YVdzUQ==
.youtube.com	TRUE	/	FALSE	0	PREF	f4=4000000&f6=40000000&tz=UTC&hl=en
.youtube.com	TRUE	/	TRUE	1769403022	SAPISID	4LXuTHdZJYTeV6z0/AF3tq8myo2ooe1R7X
.youtube.com	TRUE	/	FALSE	1769403022	SID	g.a000rgj0wk5KVoDjTbPmoqJ2hX9wqIKxO8luiwJHbkZD6vhAHQv26HMnVWMXc40V5IP3sTr48wACgYKAUASARISFQHGX2MiIsI54i4iZ-OJo8tnX-Jp-xoVAUF8yKrIogqu9CxqEJ6w90mlD0rq0076
.youtube.com	TRUE	/	FALSE	1767315991	SIDCC	AKEyXzXypyM4WJ5QAuVMBltIqVZZAXF9XX_vUiG64CaQVId51z005C1u7Rm39qD4phpUcsdv8To
.youtube.com	TRUE	/	TRUE	1769403022	SSID	AvA1jhG1rfl9-LAZY
.youtube.com	TRUE	/	TRUE	1751331991	VISITOR_INFO1_LIVE	PlNnxEi1v8U
.youtube.com	TRUE	/	TRUE	1751331991	VISITOR_PRIVACY_METADATA	CgJVUxIEGgAgbA%3D%3D
.youtube.com	TRUE	/	TRUE	0	YSC	NN06fjrPK3I
.youtube.com	TRUE	/	TRUE	1769403022	__Secure-1PAPISID	4LXuTHdZJYTeV6z0/AF3tq8myo2ooe1R7X
.youtube.com	TRUE	/	TRUE	1769403022	__Secure-1PSID	g.a000rgj0wk5KVoDjTbPmoqJ2hX9wqIKxO8luiwJHbkZD6vhAHQv2d517IL2x9ynMRnxyQA8z4gACgYKAdESARISFQHGX2MiAfIBepA5za1RQYbyS_qJMxoVAUF8yKpFivBSlL80eCEL6z5lrOqv0076
.youtube.com	TRUE	/	TRUE	1767315991	__Secure-1PSIDCC	AKEyXzVRgzj7CV86r6KyUdX1dYf5FkHWOtoZ0RQyDY02VrBo8c3hzZ-ceNXD4wuTEKCmjXM4GA0
.youtube.com	TRUE	/	TRUE	1766379022	__Secure-1PSIDTS	sidts-CjEB7wV3sR5k8XalcSi-XK-fklDA9wTgYZL4HsN-NsdD9Cpjw8wB17Wt50p2NxbAcLxWEAA
.youtube.com	TRUE	/	TRUE	1769403022	__Secure-3PAPISID	4LXuTHdZJYTeV6z0/AF3tq8myo2ooe1R7X
.youtube.com	TRUE	/	TRUE	1769403022	__Secure-3PSID	g.a000rgj0wk5KVoDjTbPmoqJ2hX9wqIKxO8luiwJHbkZD6vhAHQv2fSnSI0BLGvNdAl4jTiE65gACgYKAdQSARISFQHGX2MiPTIzzDuhQPDm3u8NruLX4RoVAUF8yKqN48TY0NzrWX1CMDQdGXCq0076
.youtube.com	TRUE	/	TRUE	1767315991	__Secure-3PSIDCC	AKEyXzWPlxa8ESZEbmnPPfMI2NFj1Q7AWNU7uLobd252bppF-B8vqpmWrFcqi5lZCSmr2uwFAQ
.youtube.com	TRUE	/	TRUE	1766379022	__Secure-3PSIDTS	sidts-CjEB7wV3sR5k8XalcSi-XK-fklDA9wTgYZL4HsN-NsdD9Cpjw8wB17Wt50p2NxbAcLxWEAA
.youtube.com	TRUE	/	TRUE	1751324775	__Secure-ROLLOUT_TOKEN	CNHj-f6Yv6unPxDrtembyrqKAxi4xrW90dWKAw%3D%3D
accounts.google.com	FALSE	/	TRUE	1769403021	ACCOUNT_CHOOSER	AFx_qI50vKBY6cI6bqlNCcuRBryM9cjFDMA2C55uATnqPupYztYwUUzqTt-ZndyhPjIVidFzchTHII1osDAr5fxYjSnWHMjiAI2WxjyyOl77DXIYo7d1dNy6bslzE71TTElnaJ7yCvl9X9DhorcrUwlFbPtpT1Anqg
accounts.google.com	FALSE	/	TRUE	1769403021	LSID	s.youtube:g.a000rgj0wu67GR75dAy8fhbfYmYgdJGCfX6EqZ7aXwfMRRFf0jh8LPuuHW5uA1nYQSb4QzAoOwACgYKARASARISFQHGX2MisbujQ4wOkJcRSwrkqZBErRoVAUF8yKqzkoiXTDX7obXMczBDRH0_0076
accounts.google.com	FALSE	/	TRUE	1737435015	OTZ	7875650_80_80_104160_76_446820
accounts.google.com	FALSE	/	TRUE	1769403021	__Host-1PLSID	s.youtube:g.a000rgj0wu67GR75dAy8fhbfYmYgdJGCfX6EqZ7aXwfMRRFf0jh8nrdpMPWNUsLsPktWdcIpYAACgYKAaYSARISFQHGX2Mi9TEuqTIyfDlqPYIlGuHSDxoVAUF8yKrK05ZbiPyq5cQI4ryHy7vj0076
accounts.google.com	FALSE	/	TRUE	1769403021	__Host-3PLSID	s.youtube:g.a000rgj0wu67GR75dAy8fhbfYmYgdJGCfX6EqZ7aXwfMRRFf0jh8Z4lWo0M9Zn5xw-mJWK64nQACgYKAXcSARISFQHGX2Min1xU0LvXqfLwhJbeNTwktRoVAUF8yKqD4_q8Kk6gEGIUzhLE_63L0076
accounts.google.com	FALSE	/	TRUE	1769403021	__Host-GAPS	1:C7USVUkOO4w4UQJslBeIvT1sqlLxwtiPsmjhL8lfOTewOvnFe3RYaTLbLPdToTNWqYx4IGOy-qzeUMH1n_96jcQKMahsOA:JQT9PU5aJO0Uoip0
` },

  { key: "submitHotkey", value: 'Enter' },
  { key: "formatHotkey", value: 'p' },
  { key: "gdriveHotkey", value: 'g' },
  { key: "getMenuHotkey", value: 'n' },
  { key: "historyMenuHotkey", value: 'm' },
  { key: "openClearHotkey", value: 'o' },
  { key: "backHotkey", value: 'Backspace' },
  { key: "autofillHotkey", value: 'f' },
  { key: "settingsHotkey", value: 's' },
]

const onlyCloudSettings = ["gdriveKeyText", "cookieText"];
const onlyLocalSettings = ["AHKPath", "focusExplorerPath", "outputPath", "gdriveJSONKey", "cookiePath"];

let storage = browser.storage.local;
let inputElements = [];



function setInputValues() {
  let cloudMode = settings.find(s => s.key === "cloudMode").value;

  console.log('cloudMode: ' + cloudMode)
  
  // subtract 1 from the length to not consider the close-footer input element
  for (let i = 0; i < inputElements.length - 1; i++) {
    let input = inputElements[i];

    if (input.classList.contains('switch-checkbox')) {
      input.checked = settings[i].value;

      // initialize the theme based on the state of the darkMode slider
      if (settings[i].key === 'darkMode') {
        document.documentElement.setAttribute('data-theme', settings[i].value ? 'dark' : 'light')
      }
    } else if (input.classList.contains('text-input')) {
      //console.log('loading from storage:')
      //console.log(settings[i].value)
      input.value = settings[i].value;
    }

    // update the visibility of settings depending on the cloudMode value
    if (cloudMode) {
      if (onlyCloudSettings.includes(settings[i].key)) {
        //console.log('setting cloud mode element ' + settings[i].key + ' to visible')
        input.parentElement.style.display = 'flex';
      } else if (onlyLocalSettings.includes(settings[i].key)) {
        //console.log('setting cloud mode element ' + settings[i].key + ' to hidden')
        input.parentElement.style.display = 'none';
      }
    } else {
      if (onlyCloudSettings.includes(settings[i].key)) {
        //console.log('setting local mode element ' + settings[i].key + ' to hidden')
        input.parentElement.style.display = 'none';
      } else if (onlyLocalSettings.includes(settings[i].key)) {
        //console.log('setting local mode element ' + settings[i].key + ' to visible')
        input.parentElement.style.display = 'flex';
      }
    }
  }

  console.log('updated input value displays');
}



function setHotkeyLabels() {
  const hotkeyLabels = document.getElementsByClassName('hotkey-text');
  const firstHotkeySetting = settings.length - hotkeyLabels.length;

  //iterate over the hotkey settings
  for (let i = firstHotkeySetting; i < settings.length; i++) {
    //set the current hotkey setting to the label value
    hotkeyLabels[i - firstHotkeySetting].textContent = settings[i].value;
    //console.log('labeled hotkey ' + settings[i].key + ' as ' + settings[i].value);
  }
}



function updateFromStorage() {
  storage.get("settings", function (result) {
    if (result.settings && result.settings.length === settings.length) {
      settings = result.settings;
      console.log('Pulled settings from storage: ', settings);
    } else {
      console.log('settings has incorrect length! storing the default values...');
      storage.set({ ['settings']: settings });
    }
    storage.set({ ['cloudMode']: settings.find(s => s.key === 'cloudMode').value })

    setInputValues();
    setHotkeyLabels();
  });
}



document.addEventListener('DOMContentLoaded', () => {
  inputElements = document.querySelectorAll('input, textarea');
  console.log('input elements: ')
  console.log(inputElements)

  updateFromStorage();


  const hotkeyListeners = new Map();

  // add the listeners for each input 
  for (let i = 0; i < inputElements.length; i++) {

    let input = inputElements[i];
    let classes = input.classList;

    if (classes.contains('switch-checkbox')) {
      input.addEventListener('click', () => {
        //store the new setting change
        console.log('new value for settings field ' + settings[i].key + ': ' + input.checked);
        settings[i].value = input.checked;
        storage.set({ ['settings']: settings });

        if (settings[i].key === 'darkMode') {
          document.documentElement.setAttribute('data-theme', settings[i].value ? 'dark' : 'light')
        } else if (settings[i].key === 'cloudMode') {
          storage.set({ ['cloudMode']: settings[i].value })
          setInputValues();
        }
      });

    } else if (classes.contains('hotkey')) {


      const handleKeyDown = (e) => handleKeyPress(e, i);


      function handleKeyPress(event, i) {
        event.preventDefault();
        const key = event.key;
        console.log('remapping hotkey ' + settings[i].key + ' from ' + settings[i].value + ' to: ' + key);

        if (!settings.find(s => (s.value === key) && (s.key !== settings[i].key))) {
          //set the setting value and store it
          settings[i].value = key;
          storage.set({ ['settings']: settings });
          // show the change on screen
          setHotkeyLabels();
        } else {
          console.log('detected duplicate key bindings! Hotkey not changed.');



          //set the hotkey-text background to red for 0.5 secs...

          const hotkeyLabels = document.getElementsByClassName('hotkey-text');
          const firstHotkeySetting = settings.length - hotkeyLabels.length;
          const hotKeyLabel = hotkeyLabels[i - firstHotkeySetting];
          hotKeyLabel.style.backgroundColor = 'red';
          setTimeout(() => {
            hotKeyLabel.style.backgroundColor = '';
          }, 500);
        }

        console.log('removing the keydown listener...')
        inputElements[i].checked = false;

        const listener = hotkeyListeners.get(i);
        if (listener) {
          window.removeEventListener('keydown', listener);
          hotkeyListeners.delete(i);
        }
      };


      function resetHotkeys(i) {
        console.log('resetting hotkeys')

        Array.from(inputElements).forEach((input, index) => {
          if ((input.classList.contains('hotkey')) && (index !== i)) {
            input.checked = false;
            const listener = hotkeyListeners.get(index);
            if (listener) {
              console.log('removing keydown listener for hotkey ' + index + '...');
              window.removeEventListener('keydown', listener);
              hotkeyListeners.delete(index);
            }
          }
        })
      }

      //console.log('listening for key press to reassign ' + settings[i].key + '...')

      input.addEventListener('click', () => {
        if (input.checked) {
          //reset all other hotkeys 
          resetHotkeys(i);
          hotkeyListeners.set(i, handleKeyDown);
          window.addEventListener('keydown', handleKeyDown);
        } else {
          const listener = hotkeyListeners.get(i);
          if (listener) {
            window.removeEventListener('keydown', listener);
            hotkeyListeners.delete(i);
          }
        }
      });
    } else if (classes.contains('text-input')) {
      console.log('adding onchange listener...')
      input.addEventListener('input', (event) => {
        let newValue = event.target.value;

        if (settings[i].key === 'maxDownloads') {
          try {
            newValue = parseInt(newValue);

            if (!newValue) {
              console.log('no new value: ' + newValue)
              newValue = 1;
              input.value = '';
            } else {
              console.log('newvalue: ' + newValue)
              newValue = Math.min(Math.max(newValue, 1), 25); // range must be between 1 - 25
              settings[i].value = newValue;

              input.value = settings[i].value;
            }
          } catch (e) {
            console.log('new maxDownloads value (' + newValue + ') is not a number! Error: ' + e.message) //dont update if it cannot be parsed into a number           
          }
        } else {
          settings[i].value = newValue;
        }

        storage.set({ ['settings']: settings });
        console.log(`Saved new value for ` + settings[i].key + `: ${newValue}`);
      });
    }
  }
});



